CREATE TABLE [dbo].[Role_TR]
(
	[Role_TRId] INT IDENTITY(1,1) NOT NULL,
	[Role] NVARCHAR(30) NOT NULL,
	[ROLE_KEY] NVARCHAR(30) NOT NULL,
	[LanguageId] INT NOT NULL,	
	
	CONSTRAINT [FK_Role_TR_Language] FOREIGN KEY ([LanguageId]) REFERENCES [dbo].[Language]([LanguageId]),
	CONSTRAINT [PK_Role_TR] PRIMARY KEY CLUSTERED ([Role_TRId] ASC),


)
